version: "3.9"

services:
  db:
    image: bitnami/postgresql:latest
    container_name: spock_db
    volumes:
      - spock_db_data:/bitnami/postgresql
    ports:
      - "6523:5432"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_DATABASE=spock

volumes:
  spock_db_data:
    driver: local